[2023-12-18T13:59:07.795+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailoperator_demo.send_email scheduled__2023-12-18T13:58:54.549498+00:00 [queued]>
[2023-12-18T13:59:07.806+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailoperator_demo.send_email scheduled__2023-12-18T13:58:54.549498+00:00 [queued]>
[2023-12-18T13:59:07.807+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-18T13:59:07.822+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): send_email> on 2023-12-18 13:58:54.549498+00:00
[2023-12-18T13:59:07.834+0000] {standard_task_runner.py:57} INFO - Started process 1167 to run task
[2023-12-18T13:59:07.838+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'emailoperator_demo', 'send_email', 'scheduled__2023-12-18T13:58:54.549498+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp2ff5eni3']
[2023-12-18T13:59:07.842+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask send_email
[2023-12-18T13:59:08.022+0000] {task_command.py:416} INFO - Running <TaskInstance: emailoperator_demo.send_email scheduled__2023-12-18T13:58:54.549498+00:00 [running]> on host 95b0d8d639bf
[2023-12-18T13:59:08.272+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='emailoperator_demo' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T13:58:54.549498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T13:58:54.549498+00:00'
[2023-12-18T13:59:08.320+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-12-18T13:59:08.321+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2023-12-18T13:59:08.321+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-12-18T13:59:08.322+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-12-18T13:59:08.486+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=emailoperator_demo, task_id=send_email, execution_date=20231218T135854, start_date=20231218T135907, end_date=20231218T135908
[2023-12-18T13:59:08.503+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task send_email ([Errno 99] Cannot assign requested address; 1167)
[2023-12-18T13:59:08.532+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-18T13:59:08.587+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
